# Generated by Django 6.0.6 on 2026-06-24 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('adresse', models.TextField(blank=True)),
                ('type_client', models.CharField(choices=[('habituel', 'Client habituel'), ('occasionnel', 'Client occasionnel')], default='habituel', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('annexe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.annexe')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneTournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_chargee', models.IntegerField()),
                ('quantite_vendue', models.IntegerField(default=0)),
                ('quantite_retournee', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='livraisons.tournee')),
            ],
        ),
    ]
