# Generated by Django 6.0.6 on 2026-06-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('montant_ouverture', models.DecimalField(decimal_places=2, default=0, help_text='Fond de caisse au départ', max_digits=10)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence MoMo si paiement mobile', max_length=100)),
                ('encaisse_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
