# Generated by Django 6.0.6 on 2026-06-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('caisse', '0001_initial'),
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='facturation.facture'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='annexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.annexe'),
        ),
        migrations.AddField(
            model_name='sessioncaisse',
            name='caissiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL),
        ),
    ]
