# Generated by Django 6.0.6 on 2026-06-24 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(help_text='Ex: palette, casier, bouteille', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='StockAnnexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('annexe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.annexe')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
            options={
                'unique_together': {('produit', 'annexe')},
            },
        ),
    ]
